### ISSUE TITLE
有linux的docker版本吗

### ISSUE THREAD

**Issue by xdchm0719** [FatPaper-1874/fatpaper-monopoly#1]
如题，就是问问

**Comment by FatPaper-1874** [comment]
docker跨平台的，你当然可以在linux的docker启动这个项目，如果你是想问如何在linux用docker启动这个项目的话，你可以打开根目录下的quick-docker-start.bat查看里面关于docker-compose的命令：
```docker compose -f ./docker-compose-local.yml -p fatpapersite up --force-recreate -d --build```
并在有docker compose的linux下运行该命令。

**Comment by YipSzeho** [comment]
大佬可以写个.sh脚本吗，麻烦了（

**Comment by YipSzeho** [comment]
> 大佬可以写个.sh脚本吗，麻烦了（

https://github.com/FatPaper-1874/fatpaper-monopoly/pull/4

**Comment by YipSzeho** [comment]
> 大佬可以写个.sh脚本吗，麻烦了（

自己写了个0v0
https://github.com/FatPaper-1874/fatpaper-monopoly/pull/4
